<?xml version="1.0" encoding="utf-8"?><Database Name="aspnetdb" Class="AspnetDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCALHOST\SQLEXPRESS;Initial Catalog=aspnetdb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnetdb" Provider="System.Data.SqlClient" />
</Database>